package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Erko
 */
public class AutorizarUsuariosView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AutorizarUsuariosView
     */
    public AutorizarUsuariosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrPendentes = new javax.swing.JScrollPane();
        tabPendentes = new javax.swing.JTable();
        lblDescricaoTabela = new javax.swing.JLabel();
        btnAutorizar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnRejeitar = new javax.swing.JButton();

        tabPendentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome Completo", "Username"
            }
        ));
        tabPendentes.setColumnSelectionAllowed(true);
        scrPendentes.setViewportView(tabPendentes);
        tabPendentes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        lblDescricaoTabela.setText("Usuarios com autorização pendente:");

        btnAutorizar.setText("Autorizar");

        btnFechar.setText("Fechar");

        btnRejeitar.setText("Rejeitar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricaoTabela)
                    .addComponent(scrPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnAutorizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRejeitar)
                .addGap(39, 39, 39)
                .addComponent(btnFechar)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblDescricaoTabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAutorizar)
                    .addComponent(btnFechar)
                    .addComponent(btnRejeitar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnAutorizar() {
        return btnAutorizar;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public JLabel getLblDescricaoTabela() {
        return lblDescricaoTabela;
    }

    public JButton getBtnRejeitar() {
        return btnRejeitar;
    }

    public JScrollPane getScrPendentes() {
        return scrPendentes;
    }

    public JTable getTabPendentes() {
        return tabPendentes;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutorizar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRejeitar;
    private javax.swing.JLabel lblDescricaoTabela;
    private javax.swing.JScrollPane scrPendentes;
    private javax.swing.JTable tabPendentes;
    // End of variables declaration//GEN-END:variables
}
