package view;

import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Erko
 */
public class EnviarNotificacaoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form EnviarNotificacaoView
     */
    public EnviarNotificacaoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDestinatarios = new javax.swing.JLabel();
        scrDestinatarios = new javax.swing.JScrollPane();
        tabDestinatarios = new javax.swing.JTable();
        lblMensagem = new javax.swing.JLabel();
        scrMensagem = new javax.swing.JScrollPane();
        txtMensagem = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Enviar Notificações");

        lblDestinatarios.setText("Destinatarios: ");

        tabDestinatarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome Completo", "Username"
            }
        ));
        tabDestinatarios.setColumnSelectionAllowed(true);
        scrDestinatarios.setViewportView(tabDestinatarios);
        tabDestinatarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        lblMensagem.setText("Mensagem:");

        txtMensagem.setColumns(20);
        txtMensagem.setRows(5);
        scrMensagem.setViewportView(txtMensagem);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrMensagem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDestinatarios)
                    .addComponent(scrDestinatarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addComponent(lblMensagem)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEnviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFechar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDestinatarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrDestinatarios, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnFechar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarActionPerformed

    public JButton getBtnEnviar() {
        return btnEnviar;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public JScrollPane getScrDestinatarios() {
        return scrDestinatarios;
    }

    public JScrollPane getScrMensagem() {
        return scrMensagem;
    }

    public JTable getTabDestinatarios() {
        return tabDestinatarios;
    }

    public JTextArea getTxtMensagem() {
        return txtMensagem;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel lblDestinatarios;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JScrollPane scrDestinatarios;
    private javax.swing.JScrollPane scrMensagem;
    private javax.swing.JTable tabDestinatarios;
    private javax.swing.JTextArea txtMensagem;
    // End of variables declaration//GEN-END:variables
}
